/**
 * Fetches the OpenAPI spec from the Chatterbox TTS API and generates TypeScript types.
 *
 * Usage:
 *   CHATTERBOX_API_URL=https://your-api-url npm run sync-api
 *
 * Or with .env file:
 *   npm run sync-api
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import "dotenv/config";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts");

async function main() {
  const apiUrl = process.env.CHATTERBOX_API_URL;
  const apiKey = process.env.CHATTERBOX_API_KEY;

  if (!apiUrl) {
    throw new Error("CHATTERBOX_API_URL environment variable is required");
  }

  if (!apiKey) {
    throw new Error("CHATTERBOX_API_KEY environment variable is required");
  }

  const openApiUrl = `${apiUrl.replace(/\/$/, "")}/openapi.json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  const response = await fetch(openApiUrl, {
    headers: {
      "x-api-key": apiKey,
    },
  });

  if (!response.ok) {
    throw new Error(
      `OpenAPI request failed: ${response.status} ${response.statusText}`,
    );
  }

  const schema: unknown = await response.json();
  const ast = await openapiTS(schema as Parameters<typeof openapiTS>[0]);
  const contents = astToString(ast);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Add header comment
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${openApiUrl}
* Generated at: ${new Date().toISOString()}
*/
  `;

  fs.writeFileSync(OUTPUT_PATH, header + contents);
  console.log(`Types written to: ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error("Failed to sync API types:", err);
  process.exit(1);
});
